export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk}"

export HBASE_HOME="${HBASE_HOME:-/opt/hbase}"

export HBASE_CONF_DIR="${HBASE_CONF_DIR:-${HBASE_HOME}/conf}"

export HBASE_LOG_DIR="${HBASE_LOG_DIR:-${HBASE_HOME}/logs}"

export HBASE_PID_DIR="${HBASE_PID_DIR:-${HBASE_HOME}/run}"

export HBASE_MANAGES_ZK="${HBASE_MANAGES_ZK:-false}"

export HBASE_OPTS="${HBASE_OPTS:--Xms512m -Xmx1024m}"

export HBASE_MASTER_OPTS="${HBASE_MASTER_OPTS:--Xms512m -Xmx1024m}"

export HBASE_REGIONSERVER_OPTS="${HBASE_REGIONSERVER_OPTS:--Xms512m -Xmx1024m}"

export HBASE_ZOOKEEPER_QUORUM="${HBASE_ZOOKEEPER_QUORUM:-zookeeper}"

export HBASE_ZOOKEEPER_CLIENTPORT="${HBASE_ZOOKEEPER_CLIENTPORT:-2181}"

export HADOOP_HOME="${HADOOP_HOME:-/opt/hadoop}"

export HADOOP_CONF_DIR="${HADOOP_CONF_DIR:-${HADOOP_HOME}/etc/hadoop}"

export HBASE_CLASSPATH="${HBASE_CLASSPATH:-${HADOOP_CONF_DIR}}"

export HBASE_HEAPSIZE="${HBASE_HEAPSIZE:-1024}"

export HBASE_JMX_OPTS="${HBASE_JMX_OPTS:-}"

export LANG="${LANG:-C.UTF-8}"

export LC_ALL="${LC_ALL:-C.UTF-8}"