export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk}"

export HIVE_HOME="${HIVE_HOME:-/opt/hive}"
export HIVE_CONF_DIR="${HIVE_CONF_DIR:-${HIVE_HOME}/conf}"

export HIVE_LOG_DIR="${HIVE_LOG_DIR:-${HIVE_HOME}/logs}"
export HIVE_PID_DIR="${HIVE_PID_DIR:-${HIVE_HOME}/run}"
export HIVE_TMP_DIR="${HIVE_TMP_DIR:-${HIVE_HOME}/tmp}"

export HADOOP_HOME="${HADOOP_HOME:-/opt/hadoop}"
export HADOOP_CONF_DIR="${HADOOP_CONF_DIR:-${HADOOP_HOME}/etc/hadoop}"

export HIVE_AUX_JARS_PATH="${HIVE_AUX_JARS_PATH:-}"

export HIVE_METASTORE_PORT="${HIVE_METASTORE_PORT:-9083}"

export HIVE_SERVER2_PORT="${HIVE_SERVER2_PORT:-10000}"
export HIVE_SERVER2_THRIFT_PORT="${HIVE_SERVER2_THRIFT_PORT:-10000}"

export HIVE_OPTS="${HIVE_OPTS:--Xms512m -Xmx1024m}"
export HIVE_METASTORE_OPTS="${HIVE_METASTORE_OPTS:--Xms512m -Xmx1024m}"
export HIVE_SERVER2_OPTS="${HIVE_SERVER2_OPTS:--Xms512m -Xmx1024m}"

export HIVE_CONF_DIR="${HIVE_CONF_DIR}"
export HADOOP_CONF_DIR="${HADOOP_CONF_DIR}"

export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"