status = error
name = SparkLogConfiguration

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{1} - %m%n

rootLogger.level = INFO
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = ConsoleAppender

logger.spark.name = org.apache.spark
logger.spark.level = INFO

logger.spark_sql.name = org.apache.spark.sql
logger.spark_sql.level = INFO

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = WARN

logger.hive.name = org.apache.hadoop.hive
logger.hive.level = WARN

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = WARN

logger.parquet.name = org.apache.parquet
logger.parquet.level = WARN